package services

import (
	"fmt"
	"go-backend/services/go-backend/internal/logx"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/google/uuid"
)

// ProcessSTTInChunks splits a video/audio file into 15-minute chunks, transcribes each, and merges results.
func ProcessSTTInChunks(inputPath string, ext string, lang string, transLang string, updateProgress func(status string, p int, logMsg string, errStr string, text string, srt string)) (string, string, error) {
	tempDir := filepath.Join(os.TempDir(), "stt_chunks_"+uuid.New().String())
	if err := os.MkdirAll(tempDir, 0755); err != nil {
		return "", "", fmt.Errorf("failed to create temp dir: %w", err)
	}
	defer os.RemoveAll(tempDir)

	updateProgress("converting", 15, "Đang phân tách tệp đa phương tiện bằng FFmpeg...", "", "", "")
	logx.Info("Splitting video/audio into chunks using FFmpeg", "input", inputPath)

	audioExt := ".mp3"
	useCopy := false
	probeCmd := exec.Command("ffprobe", "-v", "error", "-select_streams", "a:0", "-show_entries", "stream=codec_name", "-of", "default=noprint_wrappers=1:nokey=1", inputPath)
	if codecBytes, err := probeCmd.Output(); err == nil {
		codec := strings.TrimSpace(string(codecBytes))
		switch {
		case strings.Contains(codec, "aac"):
			audioExt = ".m4a"
			useCopy = true
		case strings.Contains(codec, "mp3"):
			audioExt = ".mp3"
			useCopy = true
		case strings.Contains(codec, "flac"):
			audioExt = ".flac"
			useCopy = true
		case strings.Contains(codec, "opus") || strings.Contains(codec, "vorbis"):
			audioExt = ".ogg"
			useCopy = true
		case strings.Contains(codec, "pcm") || strings.Contains(codec, "wav"):
			audioExt = ".wav"
			useCopy = true
		}
	}

	chunkPattern := filepath.Join(tempDir, "chunk_%03d"+audioExt)
	var cmd *exec.Cmd
	if useCopy {
		logx.Info("Using stream copy (no-transcode) for audio segmenting", "codec", audioExt)
		cmd = exec.Command("ffmpeg", "-y", "-i", inputPath, "-f", "segment", "-segment_time", "900", "-vn", "-c:a", "copy", chunkPattern)
	} else {
		logx.Info("Falling back to full transcode to MP3")
		audioExt = ".mp3"
		chunkPattern = filepath.Join(tempDir, "chunk_%03d.mp3")
		cmd = exec.Command("ffmpeg", "-y", "-i", inputPath, "-f", "segment", "-segment_time", "900", "-vn", "-ar", "16000", "-ac", "1", "-c:a", "libmp3lame", chunkPattern)
	}

	if out, err := cmd.CombinedOutput(); err != nil {
		logx.Error("Fast segment failed, falling back to full transcode to MP3", err, "output", string(out))
		audioExt = ".mp3"
		chunkPattern = filepath.Join(tempDir, "chunk_%03d.mp3")
		fallbackCmd := exec.Command("ffmpeg", "-y", "-i", inputPath, "-f", "segment", "-segment_time", "900", "-vn", "-ar", "16000", "-ac", "1", "-c:a", "libmp3lame", chunkPattern)
		if fallbackOut, fallbackErr := fallbackCmd.CombinedOutput(); fallbackErr != nil {
			logx.Error("FFmpeg fallback chunking failed", fallbackErr, "output", string(fallbackOut))
			return "", "", fmt.Errorf("failed to split audio file: %w", fallbackErr)
		}
	}

	files, err := ioutil.ReadDir(tempDir)
	if err != nil {
		return "", "", fmt.Errorf("failed to read chunk dir: %w", err)
	}

	var chunkFiles []string
	for _, f := range files {
		if !f.IsDir() && strings.HasPrefix(f.Name(), "chunk_") && strings.HasSuffix(f.Name(), audioExt) {
			chunkFiles = append(chunkFiles, filepath.Join(tempDir, f.Name()))
		}
	}

	if len(chunkFiles) == 0 {
		return "", "", fmt.Errorf("no chunks generated by FFmpeg")
	}

	var finalTexts []string
	var finalSrtLines []string
	srtIndexCounter := 1

	for idx, chunkPath := range chunkFiles {
		progressVal := 20 + int(float64(idx)/float64(len(chunkFiles))*75.0)
		logMsgUpload := fmt.Sprintf("Đang tải phân đoạn %d/%d lên máy chủ CapCut...", idx+1, len(chunkFiles))
		updateProgress("processing", progressVal, logMsgUpload, "", "", "")

		logx.Info("Processing chunk", "index", idx, "total", len(chunkFiles), "path", chunkPath)
		audioBytes, err := os.ReadFile(chunkPath)
		if err != nil {
			return "", "", fmt.Errorf("failed to read chunk %d: %w", idx, err)
		}

		commitRes, err := UploadAudioToCapCut(audioBytes)
		if err != nil {
			return "", "", fmt.Errorf("failed to upload chunk %d: %w", idx, err)
		}

		logMsgTranscribe := fmt.Sprintf("Đang nhận dạng phân đoạn %d/%d bằng API CapCut...", idx+1, len(chunkFiles))
		updateProgress("processing", progressVal, logMsgTranscribe, "", "", "")

		chunkText, chunkSrt, err := CreateSTTTaskAndPoll(commitRes.Vid, commitRes.Md5, commitRes.DurationMs, lang, transLang)
		if err != nil {
			return "", "", fmt.Errorf("failed transcribing chunk %d: %w", idx, err)
		}

		if chunkText != "" {
			finalTexts = append(finalTexts, chunkText)
		}

		if chunkSrt != "" {
			offsetMs := idx * 900 * 1000 // 15 minutes in ms
			shiftedSrt, nextIdx := OffsetSRT(chunkSrt, offsetMs, srtIndexCounter)
			finalSrtLines = append(finalSrtLines, shiftedSrt)
			srtIndexCounter = nextIdx
		}
	}

	return strings.Join(finalTexts, " "), strings.Join(finalSrtLines, "\n"), nil
}

// OffsetSRT parses SRT, offsets all timestamps, and adjusts subtitle index counters.
func OffsetSRT(srt string, offsetMs int, startIndex int) (string, int) {
	lines := strings.Split(strings.ReplaceAll(srt, "\r\n", "\n"), "\n")
	var result []string
	indexCounter := startIndex
	expectTime := false

	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			if len(result) > 0 && result[len(result)-1] != "" {
				result = append(result, "")
			}
			continue
		}

		// Check if it's the index line
		if _, err := strconv.Atoi(line); err == nil && !expectTime {
			result = append(result, strconv.Itoa(indexCounter))
			indexCounter++
			expectTime = true
			continue
		}

		if strings.Contains(line, "-->") {
			parts := strings.Split(line, "-->")
			if len(parts) == 2 {
				start := shiftSRTTime(strings.TrimSpace(parts[0]), offsetMs)
				end := shiftSRTTime(strings.TrimSpace(parts[1]), offsetMs)
				result = append(result, fmt.Sprintf("%s --> %s", start, end))
			} else {
				result = append(result, line)
			}
			expectTime = false
			continue
		}

		result = append(result, line)
		expectTime = false
	}

	return strings.Join(result, "\n"), indexCounter
}

func shiftSRTTime(t string, offsetMs int) string {
	var h, m, s, ms int
	_, err := fmt.Sscanf(t, "%d:%d:%d,%d", &h, &m, &s, &ms)
	if err != nil {
		return t
	}
	totalMs := h*3600000 + m*60000 + s*1000 + ms + offsetMs
	if totalMs < 0 {
		totalMs = 0
	}
	nh := totalMs / 3600000
	totalMs %= 3600000
	nm := totalMs / 60000
	totalMs %= 60000
	ns := totalMs / 1000
	nms := totalMs % 1000
	return fmt.Sprintf("%02d:%02d:%02d,%03d", nh, nm, ns, nms)
}
